default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: annablinnikova
  host: localhost

development:
  <<: *default
  database: currency_rates_dev

test:
  <<: *default
  database: currency_rates_test

production:
  <<: *default
  database: currency_rates
